### ISSUE TITLE
Open a DialogComponent from an element that is not its descendant

### ISSUE THREAD

**Issue by elias19r** [BuoySoftware/anchor_view_components#40]
An element that is not a descendant of a `DialogComponent` doesn't have access to its instance of the `dialog` Stimulus controller, so it can't call `showModal()` on it.

### Use case

- Page with a list of records and one `DialogComponent` with an empty body
- User clicks on "View details" for one of those records on the list
- A request is sent to fetch details of that record
- `DialogComponent`'s body is updated with the details
- `showModal()` is called to open the dialog so the user can read the details

#### Dispatching custom event

This can be currently done without any changes to Anchor components.

One can wrap the list and the `DialogComponent` in a `<div>` with a custom Stimulus controller that will take care of [dispatching an event](https://stimulus.hotwired.dev/reference/controllers#cross-controller-coordination-with-events) targeting any element that is inside of `DialogComponent` and has access to the `dialog` Stimulus controller instance. That element listens to the custom event and calls `showModal()`.

#### Using Stimulus Outlet

This requires changes to the `DialogComponent`: adding an `id:` attribute to it.

One could select `DialogComponent`'s instance of the `dialog` Stimulus controller by passing in its element id to a [Stimulus Outlet](https://stimulus.hotwired.dev/reference/outlets) selector in any other controller on the page and then call `showModal()` on it.

**Comment by tysongach** [comment]
@elias19r I believe this is closed by https://github.com/BuoySoftware/anchor_view_components/pull/39 - does that seem right to you? Would that work for your situation?

**Comment by tysongach** [comment]
Also https://github.com/BuoySoftware/anchor_view_components/pull/32 - which allows Dialog to accept `id`.
